//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultilayerArchitecture.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ispit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ispit()
        {
            this.StudentIspit = new HashSet<StudentIspit>();
        }
    
        public int idIspit { get; set; }
        public short idIspitniRok { get; set; }
        public short idPredmet { get; set; }
        public Nullable<System.DateTime> ispitDatum { get; set; }
    
        public virtual IspitniRok IspitniRok { get; set; }
        public virtual Predmet Predmet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentIspit> StudentIspit { get; set; }
    }
}
